### ISSUE TITLE
Bug cannot install Cli Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by stgoddv** [saleor/saleor-cli#168]
Just at the end of npm I get:

`npm ERR! code 1
npm ERR! path /home/stgod/.nvm/versions/node/v16.2.0/lib/node_modules/saleor
npm ERR! command failed
npm ERR! command sh -c node ./build/scripts/binary.js install
npm ERR! node:child_process:326
npm ERR!       ex = new Error('Command failed: ' + cmd + '\n' + stderr);
npm ERR!            ^
npm ERR! 
npm ERR! Error: Command failed: ./vendor/tunnel --version
npm ERR! ./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./vendor/tunnel)
npm ERR! ./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./vendor/tunnel)
npm ERR! ./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./vendor/tunnel)
npm ERR! ./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./vendor/tunnel)
npm ERR! 
npm ERR!     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR!     at ChildProcess.emit (node:events:365:28)
npm ERR!     at maybeClose (node:internal/child_process:1067:16)
npm ERR!     at Socket.<anonymous> (node:internal/child_process:453:11)
npm ERR!     at Socket.emit (node:events:365:28)
npm ERR!     at Pipe.<anonymous> (node:net:661:12) {
npm ERR!   killed: false,
npm ERR!   code: 1,
npm ERR!   signal: null,
npm ERR!   cmd: './vendor/tunnel --version',
npm ERR!   stdout: '',
npm ERR!   stderr: "./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./vendor/tunnel)\n" +
npm ERR!     "./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./vendor/tunnel)\n" +
npm ERR!     "./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./vendor/tunnel)\n" +
npm ERR!     "./vendor/tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./vendor/tunnel)\n"
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stgod/.npm/_logs/2022-06-28T02_56_36_060Z-debug.log
`
Im using node version:

`v16.15.1`

Also, my ubuntu version is:

`o LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
`
Dont have any Idea what could be happening here.

Someone knows something bout this?
I'm not sure about what this "vendor-tunnel" is..

**Comment by stgoddv** [comment]
¿Is is there a way to obtain the " saleor storefront create" template (with and without --demo flag) WITHOUT the cli? 
For example, is there a branch on the storefront repository of these templates? It could be very useful in cases when saleor-cli dont work.

**Comment by zaiste** [comment]
@stgoddv thanks for the report. Could you try `1.8.0-rc.1` from the `next` tag and see if it fixes the problem?

**Comment by timuric** [comment]
@stgoddv CLI simply pulls the latest version if the storefront

**Comment by zaiste** [comment]
@stgoddv This should be fixed now. Update to the latest version with:
```
npm i -g @saleor/cli@latest
```
