### ISSUE TITLE
Include permissions descriptions to CLI listing

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#209]
# Context

`saleor app permission` listing shows only the keys

![Zrzut ekranu 2022-07-27 o 15 27 28](https://user-images.githubusercontent.com/9268745/181258631-94ddad92-7b1f-46f6-87a5-2bed10a16384.png)

# Proposed solution

1. Include description from API in the listings (all permission occurencies)
2. Include [docs link](https://docs.saleor.io/docs/3.x/developer/permissions) below `Select one or more permissions`. This way CLI can link do docs from existing context.

**Comment by lkostrowski** [comment]
Waiting for @saleor/core to implement in PermissionEnum

**Comment by timuric** [comment]
90% of descriptions are saying the same thing as the name of the webhook, and some add word Access before that. Doesn’t seem to be valuable at this stage of docs.

@peelar cc
