### ISSUE TITLE
[CLI] Not enough described actions for GH login

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#210]
**Steps to reproduce the problem:**
1. Go to your apps folder as a logged-in GH user and logout on Vercel user 
2.  Use `saleor app deploy` command

**Current result:**

User doesn't get a propper message what's wrong.

```
⠏ Starting a deployment in Vercel...errors:
  message: This endpoint requires you to be authenticated.
  documentation_url: https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql
```

**Expected result:**

User is informed that should be logged in to Vercel, right now user may get confused.

**Screenshots**:

![Image](https://user-images.githubusercontent.com/25908728/181458551-7fe17ab9-6380-4cb1-b437-47d4771ee476.png)

**Comment by 2can** [comment]
@michalina-graczyk I think this has been fixed here https://github.com/saleor/saleor-cli/commit/40e3d13f99d662ad8bd51b4af681b2050e04514a

please retry

**Comment by michalina-graczyk** [comment]
Retested - I can confirm that issue doesn't exist anymore
