### ISSUE TITLE
[CLI] it should be impossible to deploy an app without an env.

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#211]
**Steps to reproduce:**
1. Create some environment
2. Create an app in that env.
3. Remove created env.
4. Do `saleor app deploy` on created app from step 2
5. Use an URL which is provided 
 
**Current result:**
I am getting an 404, but when I use `login to saleor` button then I am correctly logged in.
As a User I shouldn't get a possibility to deploy an app when environment doesn't exist anymore. 

**Expected result:**
User is getting a warning message  or user is not allowed to do this scenario.

![Image](https://user-images.githubusercontent.com/25908728/181489517-7cec4e6e-f55e-4442-b8ef-28bffce45a31.png)

https://watch.screencastify.com/v/ZArinO9z2ux6dvdY2eJp

**Comment by 2can** [comment]
Hmm I think this is an edge flow. 

To overcome this the first step after reading `NEXT_PUBLIC_SALEOR_HOST_URL` should be a ping to the environment to check if it's present. 

If not stop the deployment and show some error.

**Comment by 2can** [comment]
@lkostrowski what do you think ?

**Comment by lkostrowski** [comment]
@2can yes, be rich on errors and on checking if things are configured correctly. Don't let users to guess why error happens. So agree - check if env exist and show error if not

**Comment by zaiste** [comment]
@2can let's create an issue for that and link here, OK?

**Comment by lkostrowski** [comment]
@2can was it done recently?

**Comment by 2can** [comment]
Closing. The `.env` file is no longer used for deployment
