### ISSUE TITLE
Update `saleor storefront` for the new monorepo structure

### ISSUE THREAD

**Issue by mmiszy** [saleor/saleor-cli#213]
Update `saleor storefront` command to make it work with for the new monorepo structure in [saleor/react-storefront](https://github.com/saleor/react-storefront).

Currently `saleor storefront` is broken. It tries deploying saleor/react-storefront as if it was a single project. However, we've just recently modified its structure and it's a monorepo now. storefront is now in `apps/storefront`.

**Comment by lkostrowski** [comment]
Please write brief description what has to be done

**Comment by mmiszy** [comment]
Updated @lkostrowski 👌

**Comment by lkostrowski** [comment]
Probably related https://github.com/saleor/saleor-cli/discussions/244
