### ISSUE TITLE
[CLI] Env remove doesn't remove an env by name

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#215]
![Image](https://user-images.githubusercontent.com/25908728/181924505-4a6c8bf2-d4fd-4190-a368-5115225db053.png)

**Comment by 2can** [comment]
https://github.com/saleor/saleor-cli/pull/202
https://github.com/saleor/saleor-cli/pull/217

**Comment by 2can** [comment]
@michalina-graczyk please retry

**Comment by michalina-graczyk** [comment]
fixed
