### ISSUE TITLE
Lack of variables in the .env file results in tunnel error

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#222]
Steps to reproduce: 
- clone app-template repo
- start dev server
- in the second terminal run `saleor app tunnel`
- cli returns error ` ERROR 'app tunnel' must be run from the directory of your Saleor app`
- create an empty .env file - `touch .env`
- now tunnel starts flawlessly

**Comment by lkostrowski** [comment]
@krzysztofwolski AFAIK it was from your case, can you refine this one?

**Comment by krzysztofwolski** [comment]
@zaiste is the `.env` file requirement necessary for just starting the tunnel?

**Comment by 2can** [comment]
Closing. The `.env` file is no longer required to start the tunnel
