### ISSUE TITLE
Evaluate tooling for e2e testing of CLI

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#224]
## Context

CLI tool is not using web interface so tooling like Cypress or Playwright may not be enough.

Out users use CLI, so we should check not only programmatic, but also a manual CLI usage (mimic user behavior)

## Proposal

Evaluate tech stack that will allow to write integration/e2e tests using CLI 

## Some resources

https://asciinema.org/
https://www.smashingmagazine.com/2022/04/testing-cli-way-people-use-it/

**Comment by lkostrowski** [comment]
Elated 
https://github.com/saleor/saleor-cli/discussions/273

**Comment by michalina-graczyk** [comment]
Worth to consider: https://vitest.dev/guide/cli.html
https://docs.cypress.io/api/commands/exec#Usage

**Comment by lkostrowski** [comment]
> Worth to consider:
> 
> * https://vitest.dev/guide/cli.html
> * https://docs.cypress.io/api/commands/exec#Usage
> * https://github.com/bats-core/bats-core

Vitest here is actually their CLI (so I can run vitest with CLI, not test CLI with vitest)

bats-core - I'd not introduce entirely new technology in the stack

IMO at least first step is flow described #273 where cypress is just spawning CLI with `exec` and later goes to vercel and checks if app was deployed etc

**Comment by lkostrowski** [comment]
@zaiste @2can plese provide how to run commands with non-interactive way
