### ISSUE TITLE
Submitting apps for review to marketplace

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#225]
@lkostrowski Here's the requirement set from @mirekm 

The flow is mostly implemented (roughly ~80%)

cc @magul 

---

For the complete experience, we would like developers to be able to publish apps in the marketplace once they are done with coding and ready.

Something like:

```
saleor app publish <version> 
```

General assumptions:
- [x] MVP of publishing command would open PR for review in our marketplace repository
- [x] Let's wrap it up analogously to how npm publishing works (let's investigate in more details how does it work  )
- [x] We would need apps versioning
- [ ] We would need apps required Saleor's API
- [ ] App versions would be the releases/tags in the app's repository
- [x] We would need some manifest with the general app's name/description/etc

**Comment by lkostrowski** [comment]
@zaiste we need to discuss 2 big chunks first
1. App upgrade
2. App multi-tenancy

Let's first define how these 2 main milestones change our flow. Otherwise we risk rewrite. Do you agree?
cc @timuric

**Comment by timuric** [comment]
Submitting apps to our repository 
 has legal/security implications, we have no need to automate this process at the moment (at least not an year from now). Anyone wishing to submitting an app should first contact Saleor team.

**Comment by lkostrowski** [comment]
@timuric we can use contact form, but we have also working solution that will open a PR with app manifest added to the list.
Is this a security concern (company X can see company Y trying reach Marketplace)?

**Comment by timuric** [comment]
@lkostrowski we are only going to list repos apps that are under Saleor org

**Comment by lkostrowski** [comment]
@zaiste we did have internal discussion and we have a clearer vision of what Marketplace is meant to be.

There will be no use-case of having this functionality in CLI. 

Marketplace will serve only official apps, so we only need some private source of official apps to be fetched to Marketplace.

I suggest to remove this functionality (remove dead code complexity).
