### ISSUE TITLE
Test CLI on Windows

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#229]
There is the unresolved issue (Clickup 7534) that seems to be reproducible on Windows (only)

![image](https://user-images.githubusercontent.com/9268745/182309871-95ff866d-5bec-416d-891d-5617b0521472.png)

We should run the testing process on CLI on Windows.
Probably most of the developers in Saleor are developing on Mac/Unix - it's likely that we will not spot errors on Windows. We should consider running this test periodically

**Comment by zaiste** [comment]
@2can made a tour of CLI on vanilla Windows (no WSL) and it works. @2can can you confirm?

**Comment by 2can** [comment]
Yes, I've gone through all the commands with PowerShell. I will paste the results comment.

**Comment by 2can** [comment]
Commands tested

```
saleor info 
saleor status

saleor org list 
saleor org switch
saleor org show
saleor org permissions
saleor org remove

saleor project list 
saleor project show
saleor project create
saleor project remove

saleor logout
saleor login
saleor register - prompt doesn't open the link

saleor github login
saleor vercel login

saleor telemetry status
saleor telemetry enable
saleor telemetry disable

saleor env create
saleor env list
saleor env show
saleor env clear
saleor env populate
saleor env promote
saleor env switch
saleor env remove 

saleor backup create 
saleor backup show
saleor backup list
saleor backup restore
saleor backup remove 

saleor job list
```
