### ISSUE TITLE
Add info that user should re-login after new release version

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#237]
Right now users don't get an info that they should re-login after a new release. We should inform them in the documentation.

**Comment by lkostrowski** [comment]
@zaiste @2can is that true, that new version requires re-login, or it was some one-time situation?

**Comment by 2can** [comment]
No, there is no such requirement

**Comment by lkostrowski** [comment]
Do we have a clue with this fix the problem this one time?

**Comment by 2can** [comment]
Closing. There is no need to re-login after a new release.

One time re-login were required for Vercel & Github & Saleor Cloud due to changes in the production integrations with those API's.
