### ISSUE TITLE
Prepare Github Action to release new version of CLI

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#239]
Proposal

Create github action, can be "prepare release" or something like this

This can open a draft release with autogenerate changelogs for commit

Maintainers can prepare release message

After draft release is "released", npm publish should happen.

**Comment by lkostrowski** [comment]
@krzysztofwolski can you propose some initial process? Best if we use something that works in other repos

**Comment by lkostrowski** [comment]
@lkostrowski manage working token for pushing to protected branch

**Comment by lkostrowski** [comment]
@zaiste I don't have admin as well and don't want to be a blocker. Can you manage to set this up with @patrys help?

**Comment by patrys** [comment]
The problem with NPM tokens is that they are not scoped in any way. I can't create an NPM token limited to a single package or even a single organization.

**Comment by patrys** [comment]
I don't think you need a special GitHub token for that, you need a GitHub app with write access, and you need to create an exception for the app under branch protection rules.

**Comment by lkostrowski** [comment]
To finish:
- After github release published, run pnpm publish

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-cli/issues/456
