### ISSUE TITLE
Check if denver was properly migrated

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#245]
Tested for klaviyo 

Env for deployed app is `https://appraptor.deno.dev/register?cloud=vercel` which problably doesnt work. Envs are not set

**Comment by zaiste** [comment]
The `appraptor` from the denver suite works on Deno. I'll add some docs to describe how it works. What's the next step for this?

**Comment by lkostrowski** [comment]
I consider this done when Marketplace uses Appraptor on Vercel and app is created with this service in ENV on vercel

**Comment by lkostrowski** [comment]
CLI should use Vercel deployment

**Comment by lkostrowski** [comment]
@michalina-graczyk Testing flow - use e2e process of creating and deploying app with CLI

**Comment by michalina-graczyk** [comment]
I have created an app - works correctly
App deploy on Vercel - works correctly
After app deploy I visit dashboard page https://mgrenv.eu.saleor.cloud/dashboard/apps/install?manifestUrl=https%3A%2F%2Fapkasierpien.vercel.app%2Fapi%2Fmanifest and click `install` button 
Results on screen:


![Image](https://user-images.githubusercontent.com/25908728/187618495-ff8ed75d-5cd0-428d-a788-88d76f6ea7ed.png)

**Comment by 2can** [comment]
@michalina-graczyk I think you were too fast 😃 . From the error message it looks like the (re)deployment was still ongoing. Please retry just the installation and check if the error message will still be present.

**Comment by michalina-graczyk** [comment]
@2can no, it is not the case. After re-trying installation I have the same behavior. 
In vercel I can see that deployment token is not set 

![Image](https://user-images.githubusercontent.com/25908728/187670891-d07db998-8466-4503-bbef-0dd4eba3aeb8.png)

, but when I click edit then there is some value 

![Image](https://user-images.githubusercontent.com/25908728/187670939-08caa790-f219-4ee3-bf5a-7e9736b89285.png)

**Comment by lkostrowski** [comment]
@zaiste consider adding trace to observability with Saleor version

**Comment by zaiste** [comment]
The deployment process was fixed. We had an unexpected regression in the `appraptor` due to a wrong merge commit. 

@lkostrowski Let's do a separate issue for adding to observability.
