### ISSUE TITLE
Handle gracefully limitied Vercel's access to Github

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#246]
The CLI User should be notified that Vercel has no access to the Github repository the User is currently using.

To test that scenario you need to configure the Vercel application in Github Integrations:

1. Go to https://github.com/settings/installations and click the `Configure` button in the row with Vercel.
2. Authenticate yourself
3. In the `Repository access` section choose at least one repository for which Vercel will have access. Use `Save` button to confirm.
4. Test some Vercel command using github eg. `saleor app deploy`. Use repository for which the access hasn't been granted to the Vercel integration. As a result the following error message from Vercel should appear: `ERROR The provided GitHub repository does not contain the requested branch or commit reference. Please ensure the repository is not empty.`

Implemented in https://github.com/saleor/saleor-cli/issues/246

**Comment by lkostrowski** [comment]
@zaiste || @2can please describe this test case for @michalina-graczyk

**Comment by 2can** [comment]
@lkostrowski described

**Comment by zaiste** [comment]
`app deploy` is no longer part of CLI
