### ISSUE TITLE
Refine the Vercel API integration with error handling

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#259]
The Saleor App registration flow relies on the Vercel integration. The latter is not properly tested. We should improve the error handling and communicate the problems so that both the dashboard and CLI can inform about the app installation issues.

### How to test
- saleor app deploy
- change a character in `SALEOR_DEPLOYMENT_TOKEN`
- redeploy
- re-install

**Comment by lkostrowski** [comment]
@krzysztofwolski & @zaiste to sync on that

**Comment by zaiste** [comment]
@przlada have you managed to make this small change in the core we discussed on Friday?

**Comment by lkostrowski** [comment]
@przlada idea to include in error message source of error (vercel, core etc)

**Comment by lkostrowski** [comment]
@zaiste please describe that exact next steps must be done

**Comment by krzysztofwolski** [comment]
@zaiste The change has been merged

**Comment by michalina-graczyk** [comment]
It seems to be ok 

![Image](https://user-images.githubusercontent.com/25908728/191920620-74594763-5afe-46b2-be07-9bb745e57496.png)

After re-install I didn't get an error is it ok @zaiste ?


![Image](https://user-images.githubusercontent.com/25908728/191921108-f581e30e-1a59-4cc3-9bd3-4894dcceab4a.png)

**Comment by zaiste** [comment]
@michalina-graczyk to be verified with `1.16.0-RC.2`

**Comment by michalina-graczyk** [comment]
![Image](https://user-images.githubusercontent.com/25908728/192976166-e84e5d34-bb0d-4d6c-bb48-108267354976.png)
