### ISSUE TITLE
Checkout creation and deployment

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#261]
- Deployment of checkout together with Storefront is the critical path
- We need a way to deploy checkout like storefront
- We need to be able to create a template with storefront and checkout connected

**Comment by michalina-graczyk** [comment]
is it already implemented? My current results: https://watch.screencastify.com/v/WXV3wGEPeJZuz3xRClcR

**Comment by lkostrowski** [comment]
@michalina-graczyk CLI is only bootstrapping and deploying. Looks like it's broken somewhere later. Can you please debug with @saleor/storefront-checkout ?
