### ISSUE TITLE
Move the tunnel setup to the Cloud infra

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#263]
Unify the tunnel setup with the current infrastructure overseen by @cmiacz

**Comment by zaiste** [comment]
I've created two repositories. The [one](https://github.com/saleor/tunnel-server) is the logic for managing the virtual host and the [other one](https://github.com/saleor/tunnel-setup) is the Docker setup. Next step would be for @cmiacz to check it and try to deploy it.

**Comment by lkostrowski** [comment]
@saleor/devtools need to try it for few days and look for regressions

**Comment by lkostrowski** [comment]
@michalina-graczyk please try it with `saleor app tunnel`

**Comment by michalina-graczyk** [comment]
My results: 
 v1.14.0-rc.1 ![Image](https://user-images.githubusercontent.com/25908728/187413717-34069fd4-12c1-4471-8c10-f6726e399443.png)
