### ISSUE TITLE
cli dependencies

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#267]
### Discussed in https://github.com/saleor/saleor-cli/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **arshamkhodajoo** August  4, 2022</sup>
Hi, hope you have great time
I followed https://learn.saleor.io/setup/prerequisites/ and tried to make storefront with `saleor storefront create shop`
after few minutes guessing some dependency conflicts (with pnpm@7.8.0 throws error required explicit @7.5.0)
now the command thows this error:
` ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: next`

1. why there is no pre-requirement installation guide on website ?
2. how to fix this error</div>

**Comment by michalina-graczyk** [comment]
It works on v1.13.0
