### ISSUE TITLE
Verify the environment presence

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-cli#276]
Validate environment URL read from the `.env` file. If the environment is not present or accessible show an error.

`The '.env' file with 'VARIABLE_NAME' not found.`

`to create env, run saleor app attach`

Task linked
https://github.com/saleor/saleor-cli/issues/211

**Comment by lkostrowski** [comment]
@2can when I use existing app, I need to know how to "connect it" so CLI works.

If env doesn't exist, I'd like to create it.

Normally, CLI does it by asking me what Saleor Environment I want to use. We can do the same here.

For example

1. `saleor app deploy` fails, no env. CLI shows error
2. CLI shows hint: `to create env, run saleor app attach`
3. I type `saleor app attach`
4. CLI asks me to select environment in cloud and it creates .env file for me

This way we have "connected" flow

**Comment by 2can** [comment]
The issue for `app attach` command https://github.com/saleor/saleor-cli/issues/310

**Comment by 2can** [comment]
After deeper analysis, this verification is not necessary. 

The environment variable `NEXT_PUBLIC_SALEOR_HOST_URL` is not used by the `saleor-app-template` and it's not required for deployment. This means that `.env` file actually is not required.

**Comment by lkostrowski** [comment]
@2can we need to be able to

1. clone/forrk klavio
2. "attach" CLI to this repo, since it was not created with cli, but cloned
