### ISSUE TITLE
Not a GIT repository

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#282]
1. Create new app
2. Use `saleor app deploy`
Result:
 ERROR fatal: not a git repository (or any of the parent directories): .git
Version: 1.13.1, 1.13.0

![Image](https://user-images.githubusercontent.com/25908728/186124436-c9a7b95f-3295-4023-8883-57a3f460077e.png)

**Comment by 2can** [comment]
@michalina-graczyk `saleor app create` doesn't change the directory to the newly created app. So in your case first you need to run `cd regression13` and then `saleor app deploy`

**Comment by lkostrowski** [comment]
@2can @zaiste IMO it should show

```
To start:

cd my-app
pnpm dev
```

Instead of starting app immediately.
This is also how how some other CLIs do. What do you think?

**Comment by 2can** [comment]
I agree. The initial idea was to start fast with the template, but seems it may be more user friendly to give the user more control over it.

**Comment by zaiste** [comment]
It's not a bug. Improvements planned in https://github.com/saleor/saleor-cli/issues/284

**Comment by lkostrowski** [comment]
@2can @zaiste here is a task for mentioned proposal
https://github.com/saleor/saleor-cli/issues/287
