### ISSUE TITLE
Better info for `app create`

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#284]
Provide more descriptive info when creating a Saleor app. Also, don't start the app immediately.

**Comment by lkostrowski** [comment]
@zaiste please release 1.14@next for testing

**Comment by lkostrowski** [comment]
@michalina-graczyk please test `saleor app create` - it should not start dev server and show instructions

**Comment by michalina-graczyk** [comment]
If this insturctions are enough then it is fine. I would consider adding:
To start your application:
Go to your app folder - cd apka
Then use command - pnpm dev 

![Image](https://user-images.githubusercontent.com/25908728/187618729-a07fd9dd-d27d-45b2-a6b9-4991548aac34.png)
