### ISSUE TITLE
Display the error message for `app deploy` from wrong directory

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#285]
Show more User friendly message while triggering `saleor app deploy` in the wrong directory. Currently it's just generic error for file not found (package.json)

```
 ERROR ENOENT: no such file or directory, open '/Users/tukan/Workspace/saleor/saleor-cli/apps/package.json'
```

**Comment by lkostrowski** [comment]
Confirm it works for `@saleor/cli@1.14.0-rc.1`



![Image](https://user-images.githubusercontent.com/9268745/187164254-6c147359-a981-40b3-8b53-e14941267356.png)
