### ISSUE TITLE
Check if Vercel deployment works for Team Accounts

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#292]
While working with Vercel using Teams (Organization) account the `team_id` needs to be passed alongside token to the Vercel API calls.

The task for this issue is to verify using Organization Scope (with `team_id`) commands using Vercel API

**Comment by lkostrowski** [comment]
@2can can you refine?

**Comment by zaiste** [comment]
Deployments not posssible via CLI
