### ISSUE TITLE
No error message when creating a tunnel and app installation fails

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-cli#304]
Version: 1.13.1

Command: `saleor app install`

Tested for [`saleor-app-checkout`](https://github.com/saleor/react-storefront/tree/main/apps/saleor-app-checkout)

After running the command app installation fails which displays this unclear error message:
<img width="475" alt="CleanShot 2022-08-29 at 13 40 42@2x" src="https://user-images.githubusercontent.com/4144459/187198016-d1454cdc-0f95-4833-ad92-bbc99ab7cc2c.png">

instead of displaying error message like dashboard does:
<img width="1357" alt="CleanShot 2022-08-29 at 13 40 15@2x" src="https://user-images.githubusercontent.com/4144459/187197883-861b170a-5140-4f36-94eb-b4f083de823b.png">

**Comment by lkostrowski** [comment]
Hey @michalina-graczyk can you try to reproduce it?

**Comment by 2can** [comment]
Fixed with https://github.com/saleor/saleor-cli/pull/306
