### ISSUE TITLE
Add option to create a tunnel without app installation

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-cli#305]
Add an option to `saleor app tunnel` to create a tunnel without installing the app. This is usefull for me when debugging app installation issues or when installing app to multiple environments.

**Comment by mmiszy** [comment]
One more scenario:

1. I run `saleor app tunnel`.
2. The app gets installed (as expected) and it works.
3. I stop the tunnel for whatever reason.
4. I want to open the tunnel again so I run `saleor app tunnel`.
6. The app gets installed again (unexpected). I have to configure it again.

Would it be possible to detect that the app was previously installed and not install it again?

**Comment by witoszekdev** [comment]
> One more scenario:
> 
> 
> 
> 1. I run `saleor app tunnel`.
> 
> 2. The app gets installed (as expected) and it works.
> 
> 3. I stop the tunnel for whatever reason.
> 
> 4. I want to open the tunnel again so I run `saleor app tunnel`.
> 
> 6. The app gets installed again (unexpected). I have to configure it again.
> 
> 
> 
> Would it be possible to detect that the app was previously installed and not install it again?

I think we could had another flag so that the app is not uninstalled when tunnel is closed? Something like `--skip-uninstall`.

Then maybe we could solve this use case by having a way store and restore apps configuration by the CLI. That could be even more useful: I create a new cloud environment just to test some bug, I can copy the app's configuration from my staging environment

**Comment by zaiste** [comment]
We can add it no problem. For the context, this was like this before, but we had a discussion to force the app install in every situation...

**Comment by mmiszy** [comment]
I think a force-install should be an option `--force-install`. By default, we should only install the app if it's not installed and not install the app if it's already installed.

**Comment by mmiszy** [comment]
Adding to that – stopping the tunnel should not uninstall the app. It's counter-intuitive and you lose all the settings you've added to your app.
