### ISSUE TITLE
Create an `app attach` command

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-cli#310]
Create  `app attach` command. 

The command should show the choose environment prompt (`useToken`, `useOrganization`, `useEnvironment` middleware).

The chosen environment should be saved to the `.env` file. 

If the `.env` file with the environment endpoint already exists - the environment prompt should be  selected to that environment.

https://github.com/saleor/saleor-cli/issues/276

**Comment by lkostrowski** [comment]
@2can please remember to update docs

**Comment by 2can** [comment]
After deeper analysis, this command is not necessary. As described here https://github.com/saleor/saleor-cli/issues/276 the `.env` file is not required

**Comment by lkostrowski** [comment]
@2can we need to be able to

clone/forrk klavio
"attach" CLI to this repo, since it was not created with cli, but cloned

**Comment by 2can** [comment]
@lkostrowski attachment comes with app installation. In other words, you need to install the app to actually attach it to the saleor environment. `.env` file in reality is not needed as it's not required by either `saleor-app-klavio` or `saleor-app-templated`

**Comment by lkostrowski** [comment]
@2can I don't mean installation.

Currently flow with CLI works only if CLI created app with `app create`. 

What we need is CLI able to use the previously created repository.

For example this must work:
1. fork & pull saleor-app-klaviyo
2. [missing step]
3. run `saleor app deploy` and `saleor app install` in this app

`attach` command seems to be a good name for CLI to "hydrate" to existing app, at this point to ask for environment and create .env
