### ISSUE TITLE
Allow to define the Org/Env tuple when deploying a Saleor app

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#315]
A user must be able to define the target Saleor environment when deploying. Thus a prompt for selecting an organization + an environment must be available.

In future, this use case must also handle the situation when the Saleor API is setup locally or self-hosted.

**Comment by lkostrowski** [comment]
@2can @zaiste isn't it in progress

**Comment by zaiste** [comment]
Here's an example of how it can be used:

```
saleor app deploy --organization cli-dev --environment viSN9ix4
```
