### ISSUE TITLE
Eliminate dependency on `.env` for Saleor App

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#317]
The `.env` was used to infer the Saleor environment used in development. This is no longer needed as the current environment can be inferred from user selection for each required command i.e. `saleor app deploy` or `saleor app install`.

**Comment by lkostrowski** [comment]
Steps to reproduce - on 1.14 rc-3 (next)

Saleor app create and deploy should work without `.env` file and ask for data

**Comment by michalina-graczyk** [comment]
My test results:


![Image](https://user-images.githubusercontent.com/25908728/188592303-3ba4e811-f79e-46b0-bc7b-306e835bac40.png)

**Comment by lkostrowski** [comment]
@michalina-graczyk please report making longer timeout and better message, not related to this issue

**Comment by michalina-graczyk** [comment]
reported here: https://github.com/saleor/saleor-cli/issues/332
