### ISSUE TITLE
CLI should accept any saleor host URL in param

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#321]
Related issue (platform integration) https://github.com/saleor/saleor-cli/issues/277

CLI should accept any Saleor host as a Saleor target, eg `localhost:xxxx` with running Saleor inside Docker

CLI should be detached from cloud-only usage.

In first "stage" it can be a param-only, but probably there should be support for some local `.env` or other config file that will tell CLI that this project (folder) uses some local Saleor instance

**Comment by lkostrowski** [comment]
Related
https://github.com/saleor/saleor-cli/issues/277

**Comment by lkostrowski** [comment]
Cosndier `.saleorrc` or something like this

**Comment by lkostrowski** [comment]
Discussed with @krzysztofwolski that .saleorrc will benefit with more settings, like codegen config for generating webhook etc.

I've increased priority of this one. Its very important segment to locally integrate integration tests with local saleor instance

**Comment by zaiste** [comment]
@michalina-graczyk can we focus on this with priority?

**Comment by michalina-graczyk** [comment]
My tests steps:
1. I ve created a storefront 
2.  I ve added an instance link `https://testmgr.eu.saleor.cloud/`
3. Saleor API URL added additional `\` 

There is no validation for an address

![Image](https://user-images.githubusercontent.com/25908728/192988387-da0568ad-938e-4d40-a3d2-48b09e81416f.png)

Another thing is that when I click on deployment URL I am getting `500`
Logs from Vercel:
`[GET] /default-channel/en-US/
09:02:04:94
 '\n' +
      '    .bottom-container span {\n' +
      '        padding: 0 2rem;\n' +
      '        -webkit-box-flex: 0;\n' +
      '        -ms-flex: none;\n' +
      '        flex: none;\n' +
      '    }\n' +
      '\n' +
      '    .bottom-container button,\n' +
      '    .bottom-container span {\n' +
      '        margin-bottom: 2.5rem;\n' +
      '    }\n' +
      '\n' +
      '    .header {\n' +
      '        margin-bottom: 2rem;\n' +
      '    }\n' +
      '</style>\n' +
      '\n' +
      '<body>\n' +
      '    <header class="header">\n' +
      '        <div class="container-fluid">\n' +
      '            <a href="/" class="logo">\n' +
      '                <svg width="35" height="32" viewBox="0 0 35 32" fill="none" xmlns="http://www.w3.org/2000/svg">\n' +
      '                    <path fill-rule="evenodd" clip-rule="evenodd" d="M13.43 32c5.712 0 7.149-2.307 7.149-5.466 0-3.887-3.493-4.613-6.398-5.088-2.22-.379-3.231-.568-3.231-1.927 0-1.01.88-1.39 2.317-1.39 1.763 0 2.252.505 2.416 1.99l4.635-.695c-.392-3.191-2.187-4.802-6.92-4.802-5.19 0-7.018 2.085-7.018 5.402-.032 4.298 4.015 4.74 7.018 5.246 1.86.347 2.579.663 2.579 1.896 0 1.01-.62 1.453-2.481 1.453-2.057 0-2.677-.348-2.938-2.022l-4.504.663C6.478 30.642 8.469 32 13.43 32z"\n' +
      '                        fill="#28234A" />\n' +
      '                    <path fill-rule="evenodd" clip-rule="evenodd" d="M19.19 0l-6.187 6.446h15.282L34.472 0H19.19z" fill="#8AC4EB" />\n' +
      '                    <path fill-rule="evenodd" clip-rule="evenodd" d="M5.975 2.236a.61.61 0 01.43-.178h20.099a.61.61 0 01.43 1.04l-5.796 5.78a.61.61 0 01-.43.177H.61a.61.61 0 01-.43-1.04l5.796-5.78zm.681 1.04l-4.573 4.56h18.374l4.573-4.56H6.656z"\n' +
      '                        fill="#28234A" /></svg>\n' +
      '            </a>\n' +
      '        </div>\n' +
      '    </header>\n' +
      '    <div class="container">\n' +
      '        <div class="contentContainer">\n' +
      '            <div class="imageContainer">\n' +
      '                <svg width="785" height="751" viewBox="0 0 785 751" fill="none" xmlns="http://www.w3.org/2000/svg">\n' +
      '                    <path d="M15 348.24l29.864 14.954V318.42L15 303.466v44.774z" fill="#fff" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M74.727 303.466L44.863 318.42v44.774l29.864-14.954v-44.774z" fill="#fff" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M15 303.466l29.864 14.954V124.413L15 109.459v194.007z" fill="#EDF5F8" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M74.727 109.459l-29.864 14.954V318.42l29.864-14.954V109.459z" fill="#EDF5F8" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M15 109.459l29.864-14.91 29.864 14.91-29.864 14.954L15 109.459z" fill="#EDF5F8" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M104.55 303.466l29.864 14.954V184.097l-29.864-14.91v134.279z" fill="#fff" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <path d="M164.275 169.187l-29.864 14.91V318.42l29.864-14.954V169.187z" fill="#fff" stroke="#32335A"\n' +
      '                        stroke-linecap="round" stroke-linejoin="round" />\n' +
      '                    <pat'... 18265 more characters
  },
  extraInfo: undefined,
  page: '/[channel]/[locale]'
}
RequestId: 885888ae-549b-4f85-9e66-e33d0f4fe977 Error: Runtime exited with error: exit status 1
Runtime.ExitError`
