### ISSUE TITLE
Improve error message when Vercel has not enough permissions to the GitHub repos

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor-cli#323]
Steps to reproduce:
- connect Vercel to GitHub, but choose the option "selected repositories" instead of all
- create a new app with `saleor app create saleor-app-deployment-test`
- cd to the directory
- logged in into GitHub and Vercel
- attempt to deploy with `saleor app deploy`

Result: 
```
✔ Organization · XXX
✔ Select Environment · XXX
✔ Environment · XX - XX
Deploying saleor-app-deployment-test (the name inferred from package.json)
Deployment destination: Vercel

╭ Environment Variables ───────────────────────────────────────────────╮
│                                                                      │
│   NEXT_PUBLIC_SALEOR_HOST_URL: https://XXXXXXXXXX.eu.saleor.cloud    │
│                                                                      │
╰──────────────────────────────────────────────────────────────────────╯


 ERROR To link a GitHub repository, you need to install the GitHub integration first. Make sure there aren't any typos and that you have access to the repository if it's private.
```

Manually adding repo permissions at Vercel Dashboard has resolved the issue, but I think we can improve the error message or at least create an FAQ section with common issues/solutions.

**Comment by zaiste** [comment]
`app deploy` is no longer part of CLI
