### ISSUE TITLE
Missed info about correct name in Target URL -> webhook create

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#324]
On created app use command `saleor-test webhook create`
In target URL type incorrect address - (it's allowed so why not)

![Image](https://user-images.githubusercontent.com/25908728/188589374-146118af-fb9a-4fff-b19e-0d6090e7ffba.png)
Result:

![Image](https://user-images.githubusercontent.com/25908728/188589499-db561306-3ab2-49b1-9e38-a0259782d433.png)

If I type the correct URL then the web hook is created correctly.

![Image](https://user-images.githubusercontent.com/25908728/188589703-5812e969-1445-4bbf-bec0-8eec814bd7a8.png)

**Comment by 2can** [comment]
Closing in favor of https://github.com/saleor/saleor-cli/issues/415
