### ISSUE TITLE
Do not pass details for 5xx (or other) to clients

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#329]
Sensitive data or stack traces shouldn't be displayed in the Saleor UI. Different places it the system e.g. `appraptor` should know what to show and what to hide when such errors happen.

**Comment by lkostrowski** [comment]
To test - use DEBUG in CLI and check if there are no sensivite data printed (eg app install)

**Comment by lkostrowski** [comment]
Looks good 👍
