### ISSUE TITLE
1.14.0-rc.3 doesn’t allow me to deploy an app if I don’t have any env in my organization

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-cli#333]
Saleor-CLI 1.14.0-rc.3 doesn’t allow me to deploy an app if I don’t have any env in my organization:
```
(saleor3.9) ➜  saleor-taxjar git:(test-deployment) ✗ saleor app deploy
✔ Select Organization · Saleor-Maciek
✔ Organization · saleor-maciek

  No environments found for this organization
```
Can I somehow skip this check? Or provide my own saleor domain?

**Comment by lkostrowski** [comment]
Related
https://github.com/saleor/saleor-cli/issues/321

CLI should accept *any* Saleor host, including localhost and detach from cloud

**Comment by lkostrowski** [comment]
@zaiste @2can - can we add extra error handling for missing envs in Cloud? 

@korycins can you please provide your context of work?

**Comment by korycins** [comment]
In my case, I don't use cloud env. I am using staging cloud env, as I want to deploy an App that uses an interface that hasn't been released yet. With current approach saleor-cli force me to have at least single environment on cloud, only to build an installation url for me (afaik). 
Other scenario: You wan't to deploy an app that uses local Saleor instance (with ngrok or something) but you can't until you set-up env on saleor cloud.

**Comment by lkostrowski** [comment]
I think there is a switch between prod|stage at the moment, @zaiste @2can can you confirm?

But your case is valid, we will soon implement option to provide your own Saleor host

**Comment by zaiste** [comment]
Since `1.16` you can now set the `--url` (or `-u`) with `saleor app deploy` to specify the Saleor instance that you are targeting.

**Comment by zaiste** [comment]
There is another (blocking) problem here. As you intend to deploy a Saleor and work with your local Saleor instance, that instance must be available online so that the deploy app can reach it to initiate the installation token exchange flow. The tunnelling for Saleor platform is not yet available. This requires more discussion.

The feature implemented in #321 allows you work with your own Saleor instance as long as it's deployed somewhere and available - this is only in the context of `app deploy`.

I propose to close this issue and create a new one to cover this particular topic.

**Comment by zaiste** [comment]
@krzysztofwolski proposed to throw an exception when a `localhost` is used

**Comment by korycins** [comment]
> There is another (blocking) problem here. As you intend to deploy a Saleor and work with your local Saleor instance, that instance must be available online so that the deploy app can reach it to initiate the installation token exchange flow. The tunnelling for Saleor platform is not yet available. This requires more discussion.
> The feature implemented in https://github.com/saleor/saleor-cli/issues/321 allows you work with your own Saleor instance as long as it's deployed somewhere and available - this is only in the context of app deploy.
> 
> I propose to close this issue and create a new one to cover this particular topic.

Possibility to provide an URL is fine for me. I can use ngrok to create a tunel for my local instance. I can also use different instances from staging saleor cloud.
IMO we can close the issue.

**Comment by lkostrowski** [comment]
Good, report any issues and ideas if you have @korycins !
