### ISSUE TITLE
saleor app deploy command forces me to execute it a couple of times to get a proper feedback

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-cli#334]
`saleor app deploy` - when I tried to execute a command as a logout user, the path is a little bit annoying:
First `saleor app deploy` execution command:
```
(saleor3.9) ➜  saleor-taxjar git:(test-deployment) ✗ saleor app deploy

You are not logged into Vercel

Run saleor vercel login command to login
```
Then calling `saleor vercel login`, I am receiving:
```
(saleor3.9) ➜  saleor-taxjar git:(test-deployment) ✗ saleor vercel login
Response code 400 (Bad Request)
Tip: in some cases saleor logout followed by saleor login may help
```
Then when I execute `saleor login` and then `saleor vercel login`, I successfully logged in to  vercel.
Then I try `saleor app deploy` once again, and I am receiving:
```
(saleor3.9) ➜  saleor-taxjar git:(test-deployment) ✗ saleor app deploy

You are not logged into Github

Run saleor github login command to login
```
The output from `saleor app deploy` gives me a lot of feedback which is great, but it forces me to call the command three times to get enough info about all missing parts (missing vercel login -> missing saleor login -> missing github login).
I think that I would appreciate the bulk info that I need to execute these three commands first, or interactive flow, where saleor app deploy ask me if I would like to log in to all mandatory services.

**Comment by lkostrowski** [comment]
Proposal - create some command like `saleor status` (or similar) that will run all initial checks in parallel and report them.
eg.
```
$: saleor status

Saleor Cloud: Logged as...
Vercel: Not logged
Github: Logged as...

run saleor vercel login
```

cc @saleor/devtools putting this to board
