### ISSUE TITLE
`saleor register` should redirect to `/signup`

### ISSUE THREAD

**Issue by Cloud11PL** [saleor/saleor-cli#349]
**Describe the bug and commend which you used**
A clear and concise description of what the bug is and which command was used

**To Reproduce**
1. Run `saleor register` while being logged out from Cloud
2. You get 404 because `/register` doesn't exists in Cloud

**Current behavior**
You get 404

**Expected behavior**
You're redirected to either `/signup` or projects page

**Screenshots**

**Additional context**
`/register` no longer exists, use `/signup` instead.
Also, create an alias for `saleor register` such as `saleor signup`

**Add info from system**
Run `DEBUG=saleor-cli:*` before running a command

Run `saleor dev info` and paste the results here

**Comment by michalina-graczyk** [comment]
I am still getting 404 https://watch.screencastify.com/v/A1nRlH3T0YSMpctKkmBF 
v.1.15.0-rc.4
In incognito mode I am redirected to the sign in page https://watch.screencastify.com/v/04GgT7ZZNAQNHxaNGJ4U
