### ISSUE TITLE
Check Saleor Cloud status flags and gracefully handle them

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#364]
Some operations might be broken, when Saleor Cloud is at specific state: disabled, during upgrade, maintenance etc.

```
blocking_tasks_in_progress: bool - whether it can run any task ATM or needs to wait for some tasks to finish first
maintenance_mode: bool - whether the env is disabled for maintenance
disabled: bool - whether the env is disabled (maximum request count exceeded)
```

CLI should check them and block some commands if they will fail.

For examples, if env is disabled due to maintenance, app installation will fail. Command `app install` should be disabled and print a message how to handle it (try again later etc).

Lets create an abstraction to check these statuses, so
- They can be extended for new statuses
- They can have specific messages, hints
- They are reusable

**Comment by 2can** [comment]
Currently, we have `verifyEnvironment` in the middleware. It checks if the environment is present (200 vs 404).

https://github.com/saleor/saleor-cli/blob/main/src/middleware/index.ts#L109

**Comment by lkostrowski** [comment]
@2can does it handle maintenance mode, disabled etc? Does it print dedicated error message for these states?

**Comment by 2can** [comment]
@lkostrowski why should it handle those? `verifyEnvironment` has a different purpose. It's just a tip on where and what to extend to achieve the goal of this task

**Comment by lkostrowski** [comment]
Okay :)

**Comment by zaiste** [comment]
@2can is discussing it with the cloud team

**Comment by lkostrowski** [comment]
@NyanKiyoshi can you meet with @2can and decide what can we improve based on these flags?
