### ISSUE TITLE
Saleor checkout deploy gives an error

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#371]
Saleor Commerce CLI v1.15.0-rc.3

![Image](https://user-images.githubusercontent.com/25908728/190396086-cd060f86-7d72-4de5-8830-cee26b83f55f.png)

` saleor-cli:checkout:deploy Using the name: saleor-checkout-exm2sif7 +2ms
  saleor-cli:checkout:deploy Saleor endpoint: https://saleor-demo-pxzg5bvn.saleor.cloud/graphql/ +347ms
  saleor-cli:checkout:deploy Your Vercel token: Bearer lSCZv3TpjWlj8icW4yM40kAI +0ms
  saleor-cli:checkout:deploy App name in Vercel: saleor-checkout-exm2sif7-app +1ms
✔ Created saleor-checkout-exm2sif7-app
⠏ Deployment of saleor-checko
`

**Comment by zaiste** [comment]
@michalina-graczyk can you re-check with `1.15.2`. It should be fixed now.

**Comment by michalina-graczyk** [comment]
I have the same result @zaiste 

![Image](https://user-images.githubusercontent.com/25908728/191917336-7690868c-d947-4f98-9c82-860d69eed8f9.png)

**Comment by zaiste** [comment]
@michalina-graczyk can you test it from `main`?

**Comment by michalina-graczyk** [comment]
I ve tested it from main and gets the same results.

**Comment by 2can** [comment]
@michalina-graczyk could you provide the Vercel error message? It should be now displayed in the CLI output.

**Comment by michalina-graczyk** [comment]
@2can 
`[07:15:20.142] Cloning github.com/michalina-graczyk/sialala (Branch: main, Commit: 3983051)
[07:15:20.661] Cloning completed: 518.708ms
[07:15:20.704] Error: The specified Root Directory "apps/saleor-app-checkout" does not exist. Please update your Project Settings. Learn More: https://vercel.com/docs/build-step#root-directory`

Should this folder be added automatically or I should do it on my own?

**Comment by michalina-graczyk** [comment]
It works on 1.16.0


![Image](https://user-images.githubusercontent.com/25908728/193016422-2b19c210-fb1c-4269-b7c5-a70297a48043.png)
