### ISSUE TITLE
Saleor CLI doesn't work on ubuntu - Any commands are not responding in any way

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-cli#372]
**Describe the bug and commend which you used**
After installation of saleor-cli, try to use any command eg. "saleor info". Nothing happens.

**To Reproduce**
1. Install CLI on ubuntu- npm i -g @saleor/cli
2. Try any command eg. "saleor info"

**Current behavior**
Commands are not responding in any way, no error is displayed, and nothing is happening.

**Expected behavior**
Commands should work 

**Additional context**
version: @saleor/cli@1.14.1
node: 16
Operating System: Ubuntu-latest

**Comment by prajogoatmaja** [comment]
[issue 279](https://github.com/saleor/saleor-cli/issues/279) also have similar error, but with different error behavior. Perhaps the team can also check on the issue as well.

**Comment by zaiste** [comment]
@karola312 @prajogoatmaja this is fixed in `1.15`
