### ISSUE TITLE
App install is not woking on RC3

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#375]
**Describe the bug and commend which you used**

It is impossible to install an app in dashboard

**To Reproduce**

1. Create new app
2. Deploy it
3. Install this app via dashboard

**Current behavior**

`"data":{1 item
"appsInstallations":[1 item
0:{6 items
"status":"FAILED"
"message":"Failed to connect to app. Try later or contact with app support."
"appName":"bartekapp"
"manifestUrl":"https://bartekapp.vercel.app/api/manifest"
"id":"QXBwSW5zdGFsbGF0aW9uOjE="
"__typename":"AppInstallation"
}
]
}`

**Expected behavior**
The app is correctly installed

**Screenshots**

![image](https://user-images.githubusercontent.com/25908728/190631328-4cf3a14b-3578-4c3c-89fd-4ea0ed0a7aad.png)

**Additional context**

It works on v. 1.14.1
Run DEBUG=saleor-cli:* before running a command

Run saleor dev info and paste the results here

**Comment by 2can** [comment]
Currently, installation works and behaves exactly the same as on 1.14.1

**Comment by zaiste** [comment]
@michalina-graczyk This is not related to CLI, more likely an issue in the core. I'm closing it here and let's move the discussion internally.
