### ISSUE TITLE
The name of a Project can only contain up to 100 alphanumeric lowercase characters

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#404]
**Describe the bug and commend which you used**

**To Reproduce**

1. Go to  saleor-cli folder
2. Run `saleor checkout deploy ` command

**Current behavior**

```
Deploying Checkout to Vercel
⠏ Creating @saleor/cli-app-checkout...
 ERROR The name of a Project can only contain up to 100 alphanumeric lowercase characters and hyphens.
⠙ Creating @saleor/cli-app-checkout...%  
```

**Expected behavior**

User gets a clear information that is in the wrong catalog, or that the `saleor-cli` name must be different 

**Screenshots**

v. 1.16.0-rc.1
**Additional context**

**Comment by 2can** [comment]
Closing in favor of #404
