### ISSUE TITLE
Add webhook URL validation

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-cli#415]
`webhook create` command allows putting invalid webhook URL which makes the creation process fail on the API side

**Comment by lkostrowski** [comment]
Lets use new URL or regex to validate proper syntax. Dont try to "ping" it since it will probably be false negative

Additional idea:
- if saleor target is "internet"/cloud, additionally reject localhost webhook url
- if saleor target is localhost, allow webhook to be localhost
