### ISSUE TITLE
Always displays `offline` on Ubuntu/*nix

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#428]
**Describe the bug and commend which you used**

Any `saleor` command always displays the `offline` message on Ubuntu due to differences in the `ping` implementation between different OSes

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lkostrowski** [comment]
ensure it doesnt brake any CI workflows

**Comment by ohuu** [comment]
this is happening on windows too

**Comment by lkostrowski** [comment]
Hi @ohuu , can you give us more details whats going on?

**Comment by ohuu** [comment]
Not really, it's just that every function just returns the same error message.

![image](https://user-images.githubusercontent.com/25370730/196387796-544cf314-2e0d-4c4f-aa68-691bfb5dd18b.png)

**Comment by zaiste** [comment]
@ohuu would you mind trying the (recently released) `1.18.2`?
