### ISSUE TITLE
Consider deprecating app deploy command

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-cli#445]
Maintaining app deploy requires extra work and shares logic with vercel deploy.

Maybe this can be more "lean" and some logic can be removed

**Comment by zaiste** [comment]
`app deploy` is not doing the same thing as Vercel CLI. There is this whole process of double-deployment along with environment variables setting via app raptor. Thus, at this stage we cannot remove it, but we are working on generalising it to easily handle other providers e.g. Netlify is first on our list.

**Comment by lkostrowski** [comment]
Let me open this again, there is still open discussion on the future of this first class Vercel approach

**Comment by 2can** [comment]
Command deprecated. Closing
