### ISSUE TITLE
[Automation] Add test for `app tunnel`

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#451]
#Check if saleor tunnel starts

**Precondition**
1. App is created locally 
2. App is running on port 3000

**Test scenario**
1. Go to the app catalog
2. Use saleor app tunnel
3. Select organization
4. Select environment
5. Wait for installation

**Expected results**
1. Check if saleor app name is correct
2. Saleor app tunnel prints URL to output 
3. Calling URL should respond with HTML and status 200

**Comment by lkostrowski** [comment]
@2can lets check if curl to tunneled website works cc @michalina-graczyk

**Comment by zaiste** [comment]
confirmed with @2can as `done`
