### ISSUE TITLE
Running "saleor storefront create" on the cli: not giving any options and auto generating "demo" store

### ISSUE THREAD

**Issue by jbrown8181** [saleor/saleor-cli#490]
### Summary

When I executed: `saleor storefront create` on the the terminal command line, I expected the following as per the readme:

"...It will take you through the process of creating a new Saleor API instance (or choosing an existing one) and connecting it to your freshly cloned local storefront setup"

Instead, it setup a local "demo" storefront automatically without providing any options.

### Steps to reproduce

Execute `saleor storefront create` in an OSX terminal window

**Comment by mmiszy** [comment]
Moved the issue to the appropriate repository.

**Comment by mmiszy** [comment]
What's the version of saleor CLI you're using?

**Comment by lkostrowski** [comment]
@michalina-graczyk can you check this? Probably docs are out of date

**Comment by lkostrowski** [comment]
@2can please review and update docs and check if entire flow is accurate

**Comment by 2can** [comment]
https://github.com/saleor/react-storefront/pull/608
