### ISSUE TITLE
Inconsistency with logged in status 

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#493]
**Describe the bug and commend which you used**

When I am usin `saleor status` I am getting info that I am logged in but when I use `saleor info` then I am getting a message that I am not logged in 

**To Reproduce**

1. Use saleor status command
2. Use saleor info command
3. Compare results

**Current behavior**

![image](https://user-images.githubusercontent.com/25908728/197706920-61e6be22-85ec-48ac-8855-bcfe78dae1d5.png)

**Expected behavior**

The message about being logged in should be consistent

**Comment by lkostrowski** [comment]
1. Store Saleor token with related domain and show it - that user is logged for this env
2. Check if Vercel and Github tokens are alive each time saleor status is called
3. Log out (remove token) if saleor status token is not alive 
4. Detect unhandled promise (timeout) and handle it with proper message
