### ISSUE TITLE
Improve assertions for backup command and extend tests

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-cli#494]
Please extend tests for create backup list, create new backup, show a specific backup and remove backup. All scenarious are described here: https://www.notion.so/saleor/9fe2d64e91fd44df9d0842aa0ed3e712?v=80b07f4b22704776a342f2a22a45b314

**Comment by lkostrowski** [comment]
Putting this to low priority, backups can be performed in dashboard

**Comment by 2can** [comment]
Done
