### ISSUE TITLE
`store create` - deploy to Vercel link doesn't work

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-cli#532]
While creating a new environment there is the question of Vercel deployment. The provided LINK contains NEXT_PUBLIC_API_URI variable which seems to be no longer valid. Deployment fails.

The optional Storefront deployment to Vercel with `env create` command needs to be verified.

**Comment by lkostrowski** [comment]
@2can please describe what is the scope ?

**Comment by 2can** [comment]
Updated

**Comment by lkostrowski** [comment]
Related - this button should be updated same way

https://github.com/saleor/react-storefront/issues/466

**Comment by lkostrowski** [comment]
@saleor/storefront-checkout can you take this issue? It's connected to how storefront is builder & deployed

**Comment by mmiszy** [comment]
@lkostrowski yes. We have planning today so we'll try to add it to the nearest sprint.
