### ISSUE TITLE
Improvement: add command to generate .saleor-app-auth.json

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-cli#549]
This command would work similarly to `saleor app token` but instead of listing the token in console we would create new `.saleor-app-auth.json` file that is required for [File APL used by `saleor-app-sdk`](https://github.com/saleor/saleor-app-sdk/blob/main/docs/apl.md#fileapl).

This file looks like this:

```json
{
  "token": "(your application's auth token)",
  "domain": "(your Saleor GraphQL API URL)"
}
```

**Comment by lkostrowski** [comment]
@witoszekdev please write npm script that will "echo" output to json file. At the moment we limit new features and local FileAPL is something app-specific
