### ISSUE TITLE
CLI Google auth redirects to localhost

### ISSUE THREAD

**Issue by brightonmike** [saleor/saleor-cli#584]
**Describe the bug and commend which you used**

Using `saleor login` I then attempt to use my Google account to authorise.

**To Reproduce**

**Current behavior**

It redirects you to `https://localhost:3000/?code=5f900511-c49c-4936-a570-85b52f1fd270` 
This then means nothing happens.

**Expected behavior**

It redirects you to a web address that isn't localhost.

You can see the value is wrong here: https://auth.saleor.io/login?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F

**Screenshots**

<img width="814" alt="Screenshot 2022-12-07 at 09 55 46" src="https://user-images.githubusercontent.com/2071150/206147245-47070980-256e-4100-8a95-6fb69d6fc453.png">
<img width="865" alt="Screenshot 2022-12-07 at 09 55 54" src="https://user-images.githubusercontent.com/2071150/206147252-c6edf1c2-0f64-4da2-9528-4c1722e3536c.png">

**Comment by 2can** [comment]
@brightonmike please provide the output of `saleor dev info` so we know which version and operating system you're using

**Comment by brightonmike** [comment]
Sure, see below. The port changed today, it's trying:
"https://localhost:5375/?code=...."

```
Saleor CLI v1.24.0

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 79.84 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0
    Safari: 14.1.1
  npmPackages:
    @saleor/sdk: ^0.4.4 => 0.4.4 
```

**Comment by 2can** [comment]
@brightonmike I see that you got redirected to `https` while the CLI listens on `http`. Does your browser force `https` only ?

**Comment by brightonmike** [comment]
@2can I don't think so - having said that, some of our projects require a https proxy, these are projects using Storyblok CMS: https://www.storyblok.com/faq/setup-dev-server-https-proxy 

However this could be a red-herring as this happens even when the proxy is not running.

**Comment by c00lcoder** [comment]
Has a solution been identifies yet? I'm experiencing the exact same issue. After auth it sends to localhost and provides an error

Saleor CLI v1.28.0

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 82.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 110.0.5481.177
    Firefox: 107.0.1
    Safari: 15.6

![image](https://user-images.githubusercontent.com/90079164/224410439-eabcde0a-8171-4b35-8fe0-04f18c88cd27.png)

**Comment by c00lcoder** [comment]
For now I just went to https://cloud.saleor.io/tokens and then did `saleor configure` to manually input the access token. That seems to work in the mean time
