### ISSUE TITLE
"saleor app tunnel" fails with error message

### ISSUE THREAD

**Issue by satvikt** [saleor/saleor-cli#591]
I have been following the tutorial giving at https://learn.saleor.io/cli/creating-apps/, to create app.
Having created an app, whenever I try to create a tunnel using `saleor app tunnel`. the command fails

![Selection_072](https://user-images.githubusercontent.com/21122115/206751645-a90c86ed-b861-4f84-8073-0278dcf02cb5.png)

1. I am registered to saleor cloud and logged on terminal using `saleor login`
2.  I confirm that the prerequisites are satisfied, i.e.
    - Organization
    - Project
    - Environment
    All of these exist

Have tried several times, but I get this error every time. Please assist.

**Comment by pelonidas** [comment]
Same problem.

**Comment by avineesh-leewayhertz** [comment]
same problem any suggestion?

**Comment by 2can** [comment]
Should be fixed in 1.25.0. Please reopen if it still happens.
