### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Uponn** [saleor/saleor-cli#599]
I'm unable to login for the past 2 days, when I try npx saleor login, I get redirected in the browser, choose Continue with Google (tried with email and password also) get redirected to localhost:5375/?code=xxxxxxxxxxxxxxxxxxxxxxxxxx and "This page isn't working" "localhost is currently unable to handle this request HTTP ERROR 500"

and in the console its just stuck on
```
npx saleor login
⠧
⠇
Logging in...
Follow the instructions in your browser
```
I've tested this on Windows 10, 11 and on Mac same issue on every machine, tried 3 different accounts as well, same result.

P.S. also tried different browser, same result.

**Comment by Uponn** [comment]
by installing it by ```npm i -g @saleor/cli``` and using saleor standalone and not with npx seems to fix the issue, despite the fact that both use the same version - 1.25.0

**Comment by michalina-graczyk** [comment]
Thx for a report @Uponn, could you try it now? I was checking it and it should work now.
