### ISSUE TITLE
sealor-cli shows an error message: 

### ISSUE THREAD

**Issue by vstram** [saleor/saleor-cli#602]
I'm trying to follow the [Sealor tutorial](https://learn.saleor.io/cli/getting-started/), running the commands indicated, and unfortunatelly getting the error message below:
`You are offline. Saleor CLI requires Internet access to operate. Check your connection.`

**Current behavior**
1. Go to Powershell
2. Run `saleor login` 
3. See error

I do have an internet connection working properly.
using Windows 11 Home 21H2

**Expected behavior**
Be able to proceed with the sealor login

**Screenshots**
![image](https://user-images.githubusercontent.com/19210861/213927008-d9a46c4c-6468-4f6b-9ab4-86090629f98c.png)

**Additional context**
Is there something I'm missing out?

**Comment by vstram** [comment]
The same error occurs on Linux Mint. Any hints?
![image](https://user-images.githubusercontent.com/19210861/215267311-bc42f931-01c0-4ef1-a5ce-3e8f779f6ee9.png)

**Comment by 2can** [comment]
Please use `saleor login --headless` in case of CI, VPS, Docker environments, or environments with connectivity issues
