### ISSUE TITLE
Getting HTTP Error 500 after login on the browser when using "saleor login"

### ISSUE THREAD

**Issue by fjfricke** [saleor/saleor-cli#625]
**Describe the bug and commend which you used**

Unfortunately, I cannot login as when I use `saleor login` in the terminal and I login in the browser afterwards, I get a HTTP Error 500 when the localhost get request is called and nothing happens.

**To Reproduce**

1. Go to the terminal and enter `saleor login`
2. Log in on the browser
3. See error

**Screenshots**

This is the behaviour in the terminal. After each call to the localhost server, another "circle" appears.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/26771253/223704478-a1d35008-15d2-496c-a0ff-9959ef15dc60.png">

**Additional context**

Saleor CLI v1.28.0

  System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 148.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/opt/node@18/bin/node
    npm: 9.5.0 - /usr/local/opt/node@18/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 106.0
    Safari: 16.3

**Comment by dpaeth** [comment]
Same here

**Comment by usama-mashood** [comment]
same issue

**Comment by michalina-graczyk** [comment]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/25908728/224720137-dba68432-ac00-4f85-9fc9-1857f8a0c3c6.png">
It works from my site! Can you check on your own? @fjfricke @everestkid  @dpaeth @usama-mashood

**Comment by everestkid** [comment]
Its working now :+1:

**Comment by fjfricke** [comment]
top!

**Comment by EnriqueRBT** [comment]
Now same issue its happening to me:

Saleor CLI v1.40.0
OS: Windows11 but running saleor-cli on WSL2 Ubuntu 20.04
Node: 20.9.0.9
npm: 10.1

Thanks
