### ISSUE TITLE
Identity should not be required 

### ISSUE THREAD

**Issue by didier-moet** [saleor/saleor-cli#671]
saleor storefront create

Bullshit:
 ERROR Author identity unknown
*** Please tell me who you are.

Anonymity is KING

**Comment by zaiste** [comment]
It seems `git` isn't properly configured on your machine. This has nothing to do with «anonimity». This is required to make the experience better and more streamlined for our users.

**Comment by didier-moet** [comment]
I think I know what you mean. Thanks.
