### ISSUE TITLE
Add command for updating environment name

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-cli#679]
It would be nice to have a  command for changing the names of environments. 
We could use this command to improve our flow with automation tests on PRs, and we prefer to use CLI rather than just send requests to Cloud.

**Comment by cmiacz** [comment]
Cloud API endpoint:
![Screenshot 2023-09-29 at 10 17 52](https://github.com/saleor/saleor-cli/assets/3868440/4019c605-d460-4bab-9703-251723dc2c5d)
